/// Flutter icons AbcIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AbcIcon
///      fonts:
///       - asset: fonts/AbcIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AbcIcon {
  AbcIcon._();

  static const _kFontFam = 'AbcIcon';
  static const String? _kFontPkg = null;

  static const IconData close = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData winner = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
